apiVersion: v1
kind: Service
metadata:
  name: echosrv-echo-server
  labels:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: echosrv
    app.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: echosrv